# Generated by Django 3.2.5 on 2022-04-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('carousel_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('statusPublication', models.CharField(blank=True, choices=[('A', 'Activa'), ('D', 'Desactivada')], default='D', max_length=1)),
                ('showbuton', models.CharField(blank=True, choices=[('A', 'Activado'), ('D', 'Desactivado')], default='D', max_length=1)),
                ('linkButon', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('content1', models.TextField(max_length=1000)),
                ('content2', models.TextField(blank=True, max_length=1000, null=True)),
                ('content3', models.TextField(blank=True, max_length=1000, null=True)),
                ('background_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('publication_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('miniature_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('section', models.CharField(blank=True, choices=[('n', 'none'), ('F', 'First_Section'), ('1', 'Second_Sec_1'), ('2', 'Second_Sec_2'), ('3', 'Second_Sec_3'), ('T', 'Third_Section')], default='n', max_length=1)),
            ],
        ),
    ]
