# Generated by Django 3.2.5 on 2022-04-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('content1', models.TextField(max_length=1000)),
                ('content2', models.TextField(blank=True, max_length=1000, null=True)),
                ('content3', models.TextField(blank=True, max_length=1000, null=True)),
                ('background_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('publication_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('miniature_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('section', models.CharField(blank=True, choices=[('F', 'First_Section'), ('S', 'Second_Section'), ('T', 'Third_Section')], default='some_value', max_length=1)),
            ],
        ),
    ]
