# Generated by Django 3.2.5 on 2022-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
