# Generated by Django 3.2.5 on 2022-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20220413_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='nameButon',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
