# Generated by Django 3.2.5 on 2022-04-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_auto_20220406_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='content',
            new_name='content1',
        ),
    ]
