# Generated by Django 3.2.15 on 2022-10-17 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_carousel_namebuton'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnidadAcademica', models.CharField(max_length=250)),
                ('nombreCarrera', models.CharField(max_length=250)),
                ('logo_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('direction', models.CharField(max_length=500)),
                ('urlSite', models.CharField(max_length=500)),
                ('miniature_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('Universidad', models.CharField(blank=True, choices=[('n', 'none'), ('1', 'Universidad_1'), ('2', 'Universidad_2'), ('3', 'Universidad_3'), ('4', 'Universidad_4'), ('5', 'Universidad_5'), ('6', 'Universidad_6')], default='n', max_length=1)),
                ('carrusel_pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('cp_1_title', models.CharField(blank=True, max_length=250, null=True)),
                ('cp_1_description', models.TextField(blank=True, max_length=500, null=True)),
                ('cp_1_linkButon', models.CharField(blank=True, max_length=1000, null=True)),
                ('carrusel_pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('cp_2_title', models.CharField(blank=True, max_length=250, null=True)),
                ('cp_2_description', models.TextField(blank=True, max_length=500, null=True)),
                ('cp_2_linkButon', models.CharField(blank=True, max_length=1000, null=True)),
                ('carrusel_pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('cp_3_title', models.CharField(blank=True, max_length=250, null=True)),
                ('cp_3_description', models.TextField(blank=True, max_length=500, null=True)),
                ('cp_3_linkButon', models.CharField(blank=True, max_length=1000, null=True)),
                ('content_1', models.TextField(blank=True, max_length=2000, null=True)),
                ('content_2', models.TextField(blank=True, max_length=2000, null=True)),
                ('content_3', models.TextField(blank=True, max_length=2000, null=True)),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('file2', models.FileField(blank=True, null=True, upload_to='')),
                ('file3', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='background_pic',
        ),
        migrations.AddField(
            model_name='publication',
            name='Universidad',
            field=models.CharField(blank=True, choices=[('n', 'none'), ('1', 'Universidad_1'), ('2', 'Universidad_2'), ('3', 'Universidad_3'), ('4', 'Universidad_4'), ('5', 'Universidad_5'), ('6', 'Universidad_6')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='publication',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='linkButon',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='nameButon',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='ordenPublication',
            field=models.CharField(blank=True, choices=[('N', 'No visible'), ('1', 'Carusel 1'), ('2', 'Carusel 2'), ('3', 'Carusel 3'), ('4', 'notas')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content1',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='section',
            field=models.CharField(blank=True, choices=[('n', 'none'), ('1', 'Segunda_Sec_1'), ('2', 'Segunda_Sec_2'), ('3', 'Segunda_Sec_3'), ('T', 'Tercera_Section')], default='n', max_length=1),
        ),
    ]
