# Generated by Django 3.2.5 on 2022-04-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='section',
            field=models.CharField(blank=True, choices=[('F', 'First_Section'), ('S', 'Second_Section'), ('I', 'Second_Sec_Invert'), ('T', 'Third_Section')], default='some_value', max_length=1),
        ),
    ]
