# Generated by Django 3.2.9 on 2022-12-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_mision_objetivo_plandetrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='plandetrabajo',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
