# Generated by Django 3.2.9 on 2022-12-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_auto_20221205_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='Show',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='Show',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='plandetrabajo',
            name='Show',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
