# Generated by Django 3.2.9 on 2022-12-06 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_auto_20221206_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mision',
            old_name='Show',
            new_name='Activo',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='Show',
            new_name='Activo',
        ),
        migrations.RenameField(
            model_name='plandetrabajo',
            old_name='Show',
            new_name='Activo',
        ),
    ]
