# Generated by Django 3.2.9 on 2022-12-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_auto_20221206_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='content1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='content1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='plandetrabajo',
            name='content1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='UnidadAcademica',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='Universidad',
            field=models.CharField(blank=True, choices=[('n', 'none'), ('1', 'Universidad_1'), ('2', 'Universidad_2'), ('3', 'Universidad_3'), ('4', 'Universidad_4'), ('5', 'Universidad_5'), ('6', 'Universidad_6')], default='n', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='direction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='nombreCarrera',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='urlSite',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
