# Generated by Django 3.2.9 on 2022-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_auto_20221207_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('content1', models.TextField(blank=True, max_length=2000, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('file1', models.FileField(blank=True, null=True, upload_to='')),
                ('Activo', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
            ],
        ),
    ]
